// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAimIEiChbg7VmOvsXrC2ekSwb7HVl_T5Q',
    appId: '1:933734485463:web:25a042c5cd2a5003908f92',
    messagingSenderId: '933734485463',
    projectId: 'playpal-b9097',
    authDomain: 'playpal-b9097.firebaseapp.com',
    storageBucket: 'playpal-b9097.firebasestorage.app',
    measurementId: 'G-ENXRZ3X9R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwX2hri4-t4PpOpbiQXXiEbp4GdFd28xg',
    appId: '1:933734485463:android:32def5e80e1b74d8908f92',
    messagingSenderId: '933734485463',
    projectId: 'playpal-b9097',
    storageBucket: 'playpal-b9097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCeijcUOgDFLHLY-XvIRHsEWO6zUAiKI',
    appId: '1:933734485463:ios:c4aa7120f175643a908f92',
    messagingSenderId: '933734485463',
    projectId: 'playpal-b9097',
    storageBucket: 'playpal-b9097.firebasestorage.app',
    iosBundleId: 'com.example.labExam1Form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCeijcUOgDFLHLY-XvIRHsEWO6zUAiKI',
    appId: '1:933734485463:ios:c4aa7120f175643a908f92',
    messagingSenderId: '933734485463',
    projectId: 'playpal-b9097',
    storageBucket: 'playpal-b9097.firebasestorage.app',
    iosBundleId: 'com.example.labExam1Form',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAimIEiChbg7VmOvsXrC2ekSwb7HVl_T5Q',
    appId: '1:933734485463:web:61a8171a9d119f21908f92',
    messagingSenderId: '933734485463',
    projectId: 'playpal-b9097',
    authDomain: 'playpal-b9097.firebaseapp.com',
    storageBucket: 'playpal-b9097.firebasestorage.app',
    measurementId: 'G-SDEV4EEJLJ',
  );

}